/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f6f3f2',
        'on-secondary-fixed-variant': '#3c494f',
        'primary-fixed-dim': '#67df6e',
        'on-secondary': '#ffffff',
        'surface-bright': '#fcf9f8',
        'secondary-fixed': '#d7e4ec',
        'tertiary-container': '#84a1b0',
        'primary-fixed': '#83fc88',
        'outline': '#6e7b6a',
        'tertiary-fixed-dim': '#adcbda',
        'on-secondary-fixed': '#111d23',
        'secondary-container': '#d7e4ec',
        'on-secondary-container': '#5a666d',
        'on-tertiary-fixed-variant': '#2e4b57',
        'tertiary': '#466270',
        'inverse-surface': '#303030',
        'outline-variant': '#bdcab8',
        'on-primary-fixed-variant': '#005316',
        'on-background': '#1b1c1c',
        'on-tertiary-fixed': '#001f2a',
        'surface-tint': '#006e20',
        'on-tertiary-container': '#1a3844',
        'on-surface-variant': '#3e4a3c',
        'on-surface': '#1b1c1c',
        'on-error': '#ffffff',
        'surface-container': '#f0eded',
        'error': '#ba1a1a',
        'on-primary-container': '#003e0e',
        'surface': '#fcf9f8',
        'tertiary-fixed': '#c9e7f7',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#002205',
        'surface-variant': '#e4e2e1',
        'background': '#fcf9f8',
        'error-container': '#ffdad6',
        'primary': '#006e20',
        'surface-container-high': '#eae7e7',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e4e2e1',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#38b349',
        'secondary': '#546067',
        'inverse-primary': '#67df6e',
        'secondary-fixed-dim': '#bbc8d0',
        'surface-dim': '#dcd9d9',
        'inverse-on-surface': '#f3f0f0',
        'on-tertiary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
